### PR TITLE
Support for aws-sdk V3

### PR DESCRIPTION
**Pull request by Plitzer**
## Reason for change

AWS is slowly dropping support for aws-sdk v2 (going into maintenance mode) - you may have seen the following noisy log whenever running anything that uses it:

> Please migrate your code to use AWS SDK for JavaScript (v3). For more information, check the migration guide at https://a.co/7PzMCcy (Use node --trace-warnings ... to show where the warning was created) (node:48756) NOTE: The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.

This PR updates the implementation to support aws-sdk v3 by removing the necessity of the `.promise()` function, but keeping it in for backwards compatibility with aws-sdk v2.

The standard way to interact with aws-sdk v3 is with `Client` instances and `Command`'s:

```js
const { S3Client, GetObjectCommand } = require('@aws-sdk/client-s3')

const s3 = new S3Client({})
const response = await s3.send(new GetObjectCommand({ Bucket: 'my-bucket', Key: 'my-file.txt' }))
```

However, this library would need a full rewrite to support this pattern.
Instead, aws-sdk v3 provides wrappers that that support v2-style code, but implement the new Client/Command pattern under the hood:

```js
const { S3 } = require('@aws-sdk/client-s3')

const s3 = new S3({})
const response = await s3.getObject({ Bucket: 'my-bucket', Key: 'my-file.txt' })
```
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/#v2-compatible-style
The difference between this implementation and aws-sdk v2 is that `.promise()`'s are completely removed. Callbacks are still supported using the wrapper classes.

This means the interface for this library doesn't actually need to change, we just need to support both `.promise()` for aws-sdk v2, and lack of `.promise()` for aws-sdk v3.

As support for this v2-style may be dropped in the next major version, it would be great to rewrite this library to use the `Client` interfaces with `Command`s. Although I understand that would take considerable effort.

## Description of Changes

- Add `awsV2CompatiblePromise` to get the promise for either a v2 or v3 request
- Replace all instances of .promise() with the aws compatible promise
- Update `wrapRequest` to support v2 and v3
- Update S3 GetObject `Body` handling:
  - In v3, there is now a `transformToString` function on the body that reads the stream, `.toString()` no longer works
- Update unit tests (fully parameterised to test both v2 and v3 aws-sdk interfaces)
- Update system tests (fully parameterised to test both v2 and v3 aws-sdk instances)
- Updated README
- Version bump to 0.2.0 (non-breaking)

## Questions

- To reduce some of the complexity in the testing, you could consider only supporting the `.promise()` interface on the extended sqs client functions (e.g. `await sqsExtendedClient.sendMessage({ ... }).promise()`). This would of course no longer be a 1:1 match of the aws-sdk v3 SQS interface, but would still be familiar and work with aws-sdk v3 class instances.
- There is no linting configuration embedded in this project and my background is very typescript + 2 space tab indenting, so I did my best to keep it consistent but you may want to run whatever linting configuration you have over the project

### CODE REVIEW

**Comment by ajhofferber** [comment]
I was just looking into opening a very similar PR! This is great--hopefully it can be reviewed and merged so that this project can continue to be used with aws-sdk v3!

**Comment by Plitzer** [comment]
Any ETA on this @rod-dvla ?

**Comment by deepakthankachan** [comment]
@Plitzer could you please remove the package-lock.json file?

**Comment by deepakthankachan** [comment]
@Plitzer thanks for the contribution, will get it released this week 👍🏽

**Pull request merged**
